version: "3.5"
services:
  typesense:
    image: typesense/typesense:0.25.0
    restart: on-failure
    ports:
      - "8108:8108"
    expose:
      - '8108'
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=opannapo'